language: swift
osx_image: xcode7.2
xcode_workspace: Genome.xcworkspace
xcode_scheme: GenomeTests
xcode_sdk: iphonesimulator

before_install:
   - rvm use system
   - sudo gem install cocoapods -v '0.39.0'
